contact_links:
  - name: Ask a question
    url: https://github.com/classicvalues/classicvalues-website-update/discussions
    about: Ask and discuss questions with other Classic Values community members
